#!/usr/bin/env bash

# Run XDG autostart programs
dex -a

# Desktop shell
noctalia-shell &

# Turn off monitors on 5 minute idle
swayidle -w \
    timeout 300 "wlopm --off *" \
    resume "wlopm --on *" >/dev/null 2>&1 &
