#!/usr/bin/env bash

# Run XDG autostart programs
dex -a >/dev/null 2>&1

# Switch outputs automatically
pgrep -x kanshi >/dev/null || kanshi &

# Desktop shell
pgrep -x noctalia-shell >/dev/null || noctalia-shell &

# Turn off monitors on 5 minute idle
pgrep -x swayidle >/dev/null || \
swayidle -w \
    timeout 300 "wlopm --off *" \
    resume "wlopm --on *" &
