[bar.default]
auto_hide = true
center = [ "workspaces" ]
end = [ "tray", "network", "bluetooth", "volume", "battery", "control-center" ]
reserve_space = false
start = [ "clock", "sysmon", "spacer_2", "media" ]

[control_center]
sidebar = "full"

[dock]
auto_hide = true
enabled = true
reserve_space = false

[location]
address = "Stockholm, Sweden"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-5",
    "lockscreen-login-box@DP-6",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-5"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-6"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-6".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = false
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 712.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        clock_style = "digital"
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1020.0
    output = "DP-5"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        clock_style = "digital"
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1020.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        clock_style = "digital"
        format = "{:%H:%M:%S}"

[nightlight]
enabled = true

[shell]
font_family = "SF Pro Text"

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true

[theme]
builtin = "Rosé Pine"
community_palette = "Rose Pine Moon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "~/.config/niri"

    [wallpaper.default]
    path = "~/.config/niri/flower.jpg"

    [wallpaper.last]
    path = "~/.config/niri/flower.jpg"

    [wallpaper.monitors.eDP-1]
    path = "~/.config/niri/flower.jpg"

[widget.clock]
capsule = true
format = "{:%H:%M %a %d %b}"

[widget.network]
show_label = false

[widget.spacer_2]
type = "spacer"

[widget.sysmon]
capsule = true

[widget.tray]
capsule = true
drawer = true

[widget.workspaces]
capsule = true
