# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'rose-pine/tmux'

# Vim mode
set-window-option -g mode-keys vi

# Theme
set -g @rose_pine_variant "moon"

# Start window and pane numbering at 1 instead of 0
set-option -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Move status bar to the top
set-option -g status-position top

# CTRL+ALT+H = Select pane to the left
bind-key -n C-M-h select-pane -L

# CTRL+ALT+J = Select pane down
bind-key -n C-M-j select-pane -D

# CTRL+ALT+K = Select pane up
bind-key -n C-M-k select-pane -U

# CTRL+ALT+L = Select pane to the right
bind-key -n C-M-l select-pane -R

# ALT+J = New Window
bind-key -n M-j new-window -c "#{pane_current_path}"

# ALT+H = Select window to the left
bind-key -n M-h select-window -t :-

# ALT+L = Select window to the right
bind-key -n M-l select-window -t :+

# ALT+SHIFT+H = Move window to the left
bind-key -n M-S-h swap-window -t -1 \; select-window -t -1

# ALT+SHIFT+L = Move window to the right
bind-key -n M-S-l swap-window -t +1 \; select-window -t +1

# ALT+1 through 0 = Jump directly to windows 1-10
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
bind-key -n M-0 select-window -t 10

# CTRL+SHIFT+O = Substring picker (Enter to switch/create, Ctrl+d to delete highlighted)
bind-key -n C-S-o display-popup -w 70 -h 30 -E "\
    while true; do \
        choice=\$(tmux list-sessions -F '#{session_name}' | \
        fzf --exact --reverse \
            --header='Switch (Enter) | Create New (Enter if no match) | Delete (Ctrl+d)' \
            --print-query \
            --bind 'ctrl-d:execute(tmux kill-session -t {+})+reload(tmux list-sessions -F \"#{session_name}\")'); \
        \
        query=\$(echo \"\$choice\" | head -n 1); \
        match=\$(echo \"\$choice\" | tail -n +2); \
        \
        if [ -n \"\$match\" ]; then \
            tmux switch-client -t \"\$match\"; break; \
        elif [ -n \"\$query\" ]; then \
            tmux new-session -d -s \"\$query\" && tmux switch-client -t \"\$query\"; break; \
        else \
            break; \
        fi; \
    done"

# CTRL+SHIFT+N = Create new session
bind-key -n C-S-n command-prompt -p "New Session Name:" "new-session -A -s '%%'"

# CTRL+SHIFT+I = Jump to the previous active session
bind-key -n C-S-i switch-client -l

# ALT+R = Reload .tmux.conf (Does not reset current config, so just removing a binding does NOTHING)
bind-key -n M-r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Fix escape key delay in nvim
set -sg escape-time 0

# Set colors
set -ga terminal-overrides ",*256col*:Tc"

# Set mouse mode (to enable scrolling)
set -g mouse on

# System clipboard support using OSC 52
set -s set-clipboard on

# Use the right shell in nix..
set -gu default-command
set -g default-shell "$SHELL"

run '~/.tmux/plugins/tpm/tpm'
